name: boilerplate_code_generator
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.1.0
  boilerplate_code_annotation:
    path: ../boilerplate_code_annotation
  build: ^2.4.1
  meta: ^1.9.1
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_style: ^2.3.3
  test: ^1.23.3
